language: cpp

dist: xenial

os:
#  - linux
  - osx

compiler:
  - clang
#  - gcc

sudo: required

matrix:
  # Qt no longer supports GCC on OSX.
  allow_failures:
    - os: osx
      compiler: gcc

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; brew install qt; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get update -qq ; fi

install:
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev libqt5svg5* ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install qt5-default qttools5-dev-tools ; fi

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then chmod +x ./build_macos.sh ; fi
# - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x ./deployment/debian/deploy.sh ; fi

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then TAG_NAME=${TRAVIS_TAG} ./build_macos.sh /usr/local/opt/qt/bin/ ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then cd source; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then qmake -project ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then qmake brauhelfer.pro ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then make ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then ./deployment/debian/deploy.sh ./bin/kleiner-brauhelfer /opt/Qt/5.10.0/gcc_64/bin/ ; fi

#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100 ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100 ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x build_linux.sh ; fi
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then TAG_NAME=${TRAVIS_TAG} CXX="g++-6" CC="gcc-6" ./build_linux.sh ; fi

deploy:
  provider: releases
  api_key: $DEPLOYMENT_KEY
  file:  "./bin/kb_macos_*.zip"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: TAGS_ONLY
